### ISSUE TITLE
1.15.2 Update?

### ISSUE THREAD

**Issue by 4zy1** [J-Dill/SimpleSweep#1]
Do you plan on updating this mod for 1.15.2?

**Comment by J-Dill** [comment]
I was thinking of it, as its looking like 1.15.2 will be the next big modding version. So yes, eventually!

**Comment by J-Dill** [comment]
@4zy1 1.15.2 version of the mod has now been released! You can get it either from the [GitHub release](https://github.com/J-Dill/SimpleSweep/releases/tag/v1.0-1.15.2) or on CurseForge/Twitch Launcher.
