### ISSUE TITLE
The 1.15.2 version doesn't change anything

### ISSUE THREAD

**Issue by 4zy1** [J-Dill/SimpleSweep#2]
The sweeping edge effect still happens when this mod is enabled.

**Comment by J-Dill** [comment]
Hello @4zy1, I am not seeing that problem. When the sword does not have sweeping edge enchantment, I do not get the sweeping edge effect.

Could you explain more as far as your setup goes? ie any other mods installed, forge version, etc

Also, a new version of the mod has just been released (v1.1) so you could give that a try!

**Comment by 4zy1** [comment]
> Hello @4zy1, I am not seeing that problem. When the sword does not have sweeping edge enchantment, I do not get the sweeping edge effect.
> 
> Could you explain more as far as your setup goes? ie any other mods installed, forge version, etc
> 
> Also, a new version of the mod has just been released (v1.1) so you could give that a try!

Thanks! The new version fixed it.
