### ISSUE TITLE
blacklist/whitelist capable?

### ISSUE THREAD

**Issue by ghost** [J-Dill/SimpleSweep#3]
Hi there,

would a blacklist or whitelist be capable? I only want to remove it from SOME weapons.

**Comment by J-Dill** [comment]
Interesting thought, I haven't thought of doing that.

I think I may be able to add some sort of config option where you could white/blacklist weapons based on their registry name. I'll look more into the possibility of doing this.

**Comment by ghost** [comment]
That would be great (version 1.12.2 please :))

**Comment by J-Dill** [comment]
@roccscout New 1.12.2 release has just been uploaded to Curseforge, and you can find the whitelist and blacklist config options within the config file that gets generated on your first run with the updated version.
