### ISSUE TITLE
Blacklist and withelist in most recent versions

### ISSUE THREAD

**Issue by jahirtrap** [J-Dill/SimpleSweep#4]
You could update mod version 1.16 and add blacklist and whitelist like in version 1.12?
It is a feature that greatly improves this mod.

**Comment by J-Dill** [comment]
I was thinking of moving the feature to 1.16 version, but didn't have the motivation to do so. Seeing that atleast one person would be interested gives me some motivation, though! I'll work on moving it over to 1.16 as well.

**Comment by jahirtrap** [comment]
Ohh man :') your work is excellent i love the mod.
I'll be waiting for the update :)

**Comment by J-Dill** [comment]
@jahirtrap Update has been released! https://www.curseforge.com/minecraft/mc-mods/simple-sweep/files/3306634

Give it a try and let me know if you run into a problems.

**Comment by jahirtrap** [comment]
Excellent, thanks for the effort :)
I tested the mod and it works perfectly 👍
